version: '3.7'  # Updated to a version that supports deploy configurations
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_demo
      MYSQL_USER: lamp_demo
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  www:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  lamp-docker:
    driver: overlay
